-- 코드를 입력하세요
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(TOTAL_SALES * PRICE) AS TOTAL_SALES
FROM BOOK
JOIN (
        SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
        FROM BOOK_SALES
        WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
        GROUP BY BOOK_ID
     ) AS SUBQUERY ON BOOK.BOOK_ID = SUBQUERY.BOOK_ID
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
GROUP BY 1, 2, 3
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC;