-- 코드를 입력하세요
SELECT DISTINCT CC.CAR_ID, 
                CC.CAR_TYPE, 
                ROUND(CC.DAILY_FEE * 30 * (100 - CDP.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR            CC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  CDP ON CC.CAR_TYPE = CDP.CAR_TYPE
        AND CDP.DURATION_TYPE = '30일 이상'
WHERE CC.CAR_TYPE IN ('세단', 'SUV')
AND CC.CAR_ID NOT IN (
                        SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                        WHERE START_DATE < '2022-11-30' AND END_DATE >= '2022-11-01'
                     )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC;