SELECT
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE, 
    RI.FAVORITES,
    RI.ADDRESS,
    SUBQUERY.SCORE
FROM REST_INFO RI
JOIN (
        SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
        FROM REST_REVIEW RR
        GROUP BY REST_ID
     ) AS SUBQUERY ON RI.REST_ID = SUBQUERY.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;