-- 코드를 입력하세요
SELECT QUERY.HISTORY_ID,
       ROUND(QUERY.DAILY_FEE * QUERY.DATE * (100 - IFNULL(CDP.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM (
        SELECT CRH.HISTORY_ID, 
               CC.DAILY_FEE, 
               DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 AS DATE,
               CASE 
                    WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 90 THEN "90일 이상"
                    WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 30 THEN "30일 이상"
                    WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 7  THEN "7일 이상"
               ELSE NULL
               END AS DATE_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
        JOIN CAR_RENTAL_COMPANY_CAR CC ON CRH.CAR_ID = CC.CAR_ID 
        WHERE CAR_TYPE = '트럭' 
     ) AS QUERY
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CDP ON QUERY.DATE_TYPE = CDP.DURATION_TYPE
AND CDP.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
