-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23
)

SELECT TT.HOUR AS HOUR, COUNT(AO.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AO
RIGHT JOIN TIME_TABLE TT ON HOUR(AO.DATETIME) = TT.HOUR
GROUP BY TT.HOUR
ORDER BY TT.HOUR
